version: "2.3"
services:
  server:
    image: nvflare:server
    networks:
      backend:
        aliases:
          - server.fl.tutorial
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  client1:
    image: nvflare:client1
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  client2:
    image: nvflare:client2
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  backend:
    driver: "bridge"
